### ISSUE TITLE
Support multiple files per-entity/relationship type

### ISSUE THREAD

**Issue by suciokhan** [bayer-science-for-a-better-life/grami#19]
I have hundreds of files for a dataset with ~100 million records where in many cases a single entity type's records are spread across 20 different files. From the dataConfig.json example, it appears I can only associate a single .csv file to a given entity/relationship type at a time. It would be quite nice to be able to configure multiple dataPaths for all the different files I have for a single entity type rather than have to have 20 different config files that I have to run separately.

**Comment by suciokhan** [comment]
Perhaps allow something like `"dataPath": ['/list/of/paths1',/list/of/paths1',...] ?`

**Comment by hkuich** [comment]
thanks for this - will implement this as soon as 2.0 is stabilized! Will let you know!

**Comment by hkuich** [comment]
implementation finished - testing thoroughly now...

**Comment by hkuich** [comment]
fixed an released @suciokhan
