### ISSUE TITLE
clearer error messages for end-users

### ISSUE THREAD

**Issue by suciokhan** [bayer-science-for-a-better-life/grami#21]
Error messages in Grami are a little vague.

Example: `com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 135 column 10 path $.[4].conceptGenerators`

Something is wrong with a .json file, but which one? There are 4 at play during ingest.

**Comment by hkuich** [comment]
@suciokhan : I am planning on writing a data config / processor config validator that checks these against each other and the supplied schema before each migration - and if anything doesn't line up/make sense, to give that in better detail. I agree, most error messages are difficult to understand. Thanks for the feedback, will let you know!

**Comment by hkuich** [comment]
much improved through config validation @suciokhan
