### ISSUE TITLE
More specific WARN logging

### ISSUE THREAD

**Issue by suciokhan** [bayer-science-for-a-better-life/grami#22]
Request specific row number be captured in grami-log.log where there is an issue.

For example- in a dataset of 44 million rows:

`10:49:06.448 [main] INFO  com.bayer.dt.grami - processed 4950k rows`

`10:49:06.458 [main] WARN  com.bayer.dt.grami.data - current row has column of type <datetime> with non-<ISO 8601 format> datetime value:`

`10:49:06.458 [main] WARN  com.bayer.dt.grami.data - Text 'pub_date' could not be parsed at index 0`

`10:49:07.438 [main] INFO  com.bayer.dt.grami - processed 5000k rows`

While this is certainly helpful, I have to review 50,000 rows to find the specific problem.

**Comment by hkuich** [comment]
@suciokhan : I suppose the better solution would be to tell you exactly the row index... Do you have any other ideas?

**Comment by hkuich** [comment]
@suciokhan : will be part of next release - implementation finished.
